version: "3"
services:
  redis:
    image: redis:latest
    container_name: "ce_redis"
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: "ce_rabbitmq3.8"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=tests
    volumes:
      - ./var/rabbitmq:/var/lib/rabbitmq

  worker:
    build: .
    command: celery -A celery_entry.celery_app worker -n worker -Q test-queue -l info -c 1
    environment:
      - RABBITMQ_HOST=rabbit
      - REDIS_HOST=redis
      - C_FORCE_ROOT=True
    volumes:
      - .:/code
