version: "3"
services:
  redis:
    image: redis:latest
    container_name: "ce_redis"
    ports:
      - "6379:6379"

  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: "ce_rabbitmq3.8"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./var/rabbitmq:/var/lib/rabbitmq

  worker:


